# Dockerfile.postgres

FROM postgres:14


# Installer Git et OpenSSH
RUN apt-get update && \
    apt-get install -y git openssh-client && \
    rm -rf /var/lib/apt/lists/*


# #Préparer le répertoire SSH et copier la clé privée
RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
COPY ./.ssh/id_rsa /root/.ssh/id_rsa
RUN chmod 400 /root/.ssh/id_rsa
RUN ssh-keyscan -t rsa -H github.com >> /root/.ssh/known_hosts


# Cloner le dépôt avec Git 
RUN rm -rf /tmp \
    && mkdir -p /tmp \
    && git clone git@github.com:mariametalents/dmp_v2.git /tmp \
    && cd /tmp

# Define environment variables for remote access
ENV POSTGRES_USER=jirauser
ENV POSTGRES_DB=dmp

#RUN psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f backup_db/achats-talent/backup_dmp.sql


# Copier le script d'initialisation et le fichier de sauvegarde SQL
COPY ./init-db.sh /docker-entrypoint-initdb.d/
COPY ./backup_db/achats-talent/backup_dmp.sql /docker-entrypoint-initdb.d/

# Commande pour restaurer la sauvegarde SQL
RUN psql -U "$POSTGRES_USER" -d dmp -f /docker-entrypoint-initdb.d/backup_dmp.sql
RUN rm -rf /root/.ssh
# Commande par défaut pour démarrer PostgreSQL
CMD ["postgres"]
# # Octroyer les droits à l'instance Jira
#  RUN chown -R jira:jira /opt/atlassian/jira \
#  && chmod -R 755 /opt/atlassian/jira
#  RUN chown -R jira:jira /var/atlassian/application-data/jira \
#  && chmod -R 755 /var/atlassian/application-data/jira 
# Commande par défaut pour démarrer Jira
#CMD ["start-jira.sh", "-fg"]


