version: '3'

services:
  jira:
    image: atlassian/jira-software:latest
    ports:
      - "8080:8080"
    volumes:
      - jira-home:/var/atlassian/application-data/jira
      - ./config/server.xml:/opt/atlassian/jira/conf/server.xml
      - ./config/dbconfig.xml:/var/atlassian/application-data/jira/dbconfig.xml
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jiradb
      - ATL_JDBC_USER=jirauser
      - ATL_JDBC_PASSWORD=secretpassword

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jirauser
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  jira-home:
  db-data:
